# Generated by Django 4.0.5 on 2022-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='casual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='contemporary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='ethnic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='feminine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='genderless',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='manish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='natural',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='sporty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='subculture',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='traditional',
            field=models.IntegerField(default=0),
        ),
    ]
